version: '3.8'

services:
  db:
    container_name: bot_db
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    image: postgres:15.2-alpine3.17

  backend:
    build: ../
#    image: habo3hnk/foodgram_backend
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env